server:
  port: 8080
spring:
  application:
    name: order-service
  profiles:
    active: @profile.name@
  cloud:
    nacos:
      discovery:
        server-addr: 43.140.242.83:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8100 #sentinel控制台地址
        client-ip: 127.0.0.1opencode

    loadbalancer:
      nacos:
        enabled: true
# 设置 Mybatis 的 xml 保存路径
mybatis:
  configuration: # 配置打印 MyBatis 执行的 SQL
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  #自动驼峰转换
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %c %M %L [%thread] %m%n'
    file: '%d{HH:mm:ss.SSS} %c %M %L [%thread] %m%n'