server:
  port: 8080

spring:
  application:
    name: blog-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_blog?characterEncoding=utf8&useSSL=false
    username: root
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr:  ${nacos.address}


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  file:
    path: logs/springboot.log
    name: blog.log



---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
nacos:
  address: 43.140.242.83:8848
mysql:
  password: Cz.200406146737

---
#生产环境
spring:
  config:
    activate:
      on-profile: prod
nacos:
  address: 127.0.0.1:8848
mysql:
  password: Cz.040614